version: '3'
services:
  socket:
    image: 'ooe1/DOCKERREPO:TAG'
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.socket.rule=Host(`www.domain.com`) || Host(`domain.io`)
        - traefik.http.routers.socket.entrypoints=websecure
        - traefik.http.routers.socket.tls.certresolver=letsencryptresolver
        - traefik.http.services.socket.loadbalancer.server.port=80
networks:
  traefik-public:
    external: true